### ISSUE TITLE
Any plans for this repo?

### ISSUE THREAD

**Issue by itegebo** [valeriobasile/unboxer#1]
I'm reading your dissertation and wondered if you had any plans to add the related datasets and software.

**Comment by valeriobasile** [comment]
I'm very sorry, I missed the github notification completely.
Somehow I dropped the plans to publish the code written for the thesis because it needs cleaning etc. but if you are interested in some specific parts I'm happy to get back to it. 
The software I wrote for learning to rank (for the experiments in Chapter 5) is published in another repository: https://github.com/valeriobasile/listnet

**Comment by itegebo** [comment]
I'm interested in being able to take output from boxer and go all the way through surface realization.  Is it possible to make the code available in its current state?

As an aside, do you know if its possible to run boxer/C&C tools locally?  I found the demo and REST API, but I'm also interesting in that side as well.  Thanks!

**Comment by valeriobasile** [comment]
Sorry for taking long, but I wanted to address these issues properly. There are several points here, let me break them down.

1) Surface realization. I just uploaded the code to the repository. It is not very well documented, as it was not meant for broad publication, but I'll try and clean it up. Be sure to install the dependencies with pip install -r requirements.txt

2) The C&C tools, including Boxer, are not developed by me, and it seems that they have been discontinued. However, I included a snapshot of their repository before their server went down as part of my KNEWS software source code: https://github.com/valeriobasile/learningbyreading. There is an helper script install_candc.sh in the ext directory. I think Boxer only works with older (~6) versions of SWI Prolog.
Another thing you can try is to access the C&C tools from the HTTP API that I maintain: http://valeriobasile.github.io/candcapi/, but you seem to know that already.

3) The surface order prediction from Chapter 5 is based on supervised learning. It never wroked well and the code to extract the features from LDRGs and build a training set is a mess. If you are interested in that part, I'm happy to help, but I think the best course is to reimplement it.

4) The Ksel algorithm for lexical choice from Chapter 6 needs polishing before I put it online. However, it is not hard to implement, the most complex parts being the WordNet similarity metrics that you can find directly in NLTK.

I hope this helps a bit. Feel free to email me to further discuss your plans in NLG.
